name: treafik

networks:
  traefik_network:
    name: traefik_network

secrets:
  cloudflare_zone_token:
    environment: CLOUDFLARE_ZONE_TOKEN
  cloudflare_dns_token:
    environment: CLOUDFLARE_DNS_TOKEN

services:
  passwd-gen:
    image: httpd
    command:
      - htpasswd
      - -bc
      - /auth/users.txt
      - admin
      - ${TRAEFIK_DASHBOARD_PASSWD}
    volumes:
      - auth:/auth

  revproxy:
    depends_on:
      - passwd-gen
    image: traefik
    command:
      - --log.level=DEBUG
      - --api.dashboard=true

      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik_network

      - --entryPoints.http.address=:80
      - --entrypoints.https.address=:443

      # We redirect all HTTP traffic to HTTPS
      - --entrypoints.http.http.redirections.entrypoint.to=https
      - --entrypoints.http.http.redirections.entrypoint.scheme=https
      - --entrypoints.http.http.redirections.entrypoint.permanent=true
      # We enable TLS for all HTTPS traffic
      - --entrypoints.https.http.tls=true
      - --entrypoints.https.http.tls.certresolver=letsencrypt

      # ACME
      - --certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json

      # We switch to DNS-01 challenge to generate certificates
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.delayBeforeCheck=30
    secrets:
      - cloudflare_zone_token
      - cloudflare_dns_token
    environment:
      CLOUDFLARE_ZONE_API_TOKEN_FILE: /run/secrets/cloudflare_zone_token
      CLOUDFLARE_DNS_API_TOKEN_FILE: /run/secrets/cloudflare_dns_token
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.entryPoints: https
      traefik.http.middlewares.basic-auth.basicauth.usersFile: /auth/users.txt
      traefik.http.routers.traefik.rule: Host(`traefik.${FQDN}`)
      # Enable the `basic-auth` middleware for this router
      traefik.http.routers.traefik.middlewares: basic-auth
      ## Service
      traefik.http.routers.traefik.service: api@internal
    networks:
      - traefik_network
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - auth:/auth

volumes:
  auth:
